name: bip39
description: Dart implementation of Bitcoin BIP39 Mnemonic code for generating deterministic keys
version: 1.0.3
homepage: https://github.com/anicdh/bip39
author: anicdh <email@example.com>

environment:
  sdk: '>=2.0.0-dev.58.0 <3.0.0'

dependencies:
  pointycastle: #1.0.2 - DONE: secure code reviewd d106a92
    git:
      url: git://github.com/KomodoPlatform/pc-dart.git
      ref: d106a9218a9df81ef4e0ab239ce5db2fcd9a7435
  hex: # ^0.1.2 - DONE: secure code reviewed 6afb93f
    git:
      url: git://github.com/KomodoPlatform/dart-hex.git
      ref: 6afb93fbe9024b174bf7075338e7ca0fe9c0411b
  crypto: ^2.0.3 # dart.dev
dev_dependencies:
  test: ^1.0.0 # dart.dev
